Feat/use wc webapp
Azure-Samples/azure-search-openai-javascript pull request #70
Opened 2023-10-09 14:54 UTC by manekinekko

Closes #69

2023-10-16 14:24 UTC, anfibiacreativa approved these changes

2023-10-16 14:24 UTC, anfibiacreativa commented on packages/chat-component/src/main.ts
> +      if (this.useStream) {
conventionally booleans are named isName or hasName...do we really want to change that?

2023-10-16 14:24 UTC, anfibiacreativa commented on packages/chat-component/src/style.ts
> +  .form__container-sticky {
I like this!

2023-10-17 08:10 UTC, sinedied requested changes
I'll rebase the branch and make the changes I commented

2023-10-17 08:10 UTC, sinedied commented on packages/webapp/package.json
> +    "chat-component": "file:../chat-component",
Must be installed the "regular" way within an NPM workspace, otherwise it may cause issues

2023-10-17 08:10 UTC, sinedied commented on packages/webapp/src/pages/oneshot/OneShot.tsx
> +  const [apiEndpoint, setApiEndpoint] = useState<string>('http://localhost:3000');
The endpoint should come from the env var available in api,ts

2023-10-17 08:10 UTC, sinedied commented on packages/webapp/src/pages/chat/Chat.tsx
> +  const [apiEndpoint, setApiEndpoint] = useState<string>('http://localhost:3000');
Endpoint should come from the env var in api.ts

2023-10-17 14:54 UTC, merged